[package]
name = "csi-driver"
description = "CSI Driver"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "csi-controller"
path = "src/bin/controller/main.rs"

[[bin]]
name = "csi-node"
path = "src/bin/node/main.rs"


[build-dependencies]
tonic-build = "0.8.0"
prost-build = "0.11.1"

[dependencies]
prost = "0.11.0"
prost-derive = "0.11.0"
prost-types = "0.11.1"
tonic = "0.8.0"

anyhow = "1.0.44"
async-stream = "0.3.2"
futures = { version = "0.3.21", default-features = false }
humantime = "2.1.0"
once_cell = "1.8.0"
regex = "1.6.0"
rpc = { path = "../../rpc" }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
clap = "2.33.3"
nix = "0.22.3"
strum = "0.21.0"
strum_macros = "0.21.1"
heck = "0.4.0"

# Tracing
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = [ "env-filter" ] }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.17.4"
opentelemetry = { version = "0.17.0", features = ["rt-tokio-current-thread"] }

async-trait = "0.1.51"
chrono = "0.4.19"
glob = "0.3.0"
lazy_static = "1.4.0"
serde_json = "1.0.82"
snafu = "0.7.1"
sys-mount = "1.3.0"
tower = { version = "0.4.13", features = [ "timeout", "util" ] }
udev = "0.6.2"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
which = "4.2.2"
k8s-openapi = { version = "0.15.0", features = ["v1_20"] }
kube = { version = "0.74.0", features = ["runtime", "derive"] }
devinfo = { path = "../../utils/dependencies/devinfo" }
nvmeadm = { path = "../../utils/dependencies/nvmeadm" }
sysfs = { path = "../../utils/dependencies/sysfs" }
common-lib = { path = "../../common" }
utils = { path = "../../utils/utils-lib" }
shutdown = { path = "../../utils/shutdown" }

[dependencies.serde]
features = ["derive"]
version = "1.0.140"
